### ISSUE TITLE
ENH: fetch publication metadata with `get-metadata`

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/q2-fondue#102]
As a plugin user, I would like to also fetch publication metadata when I use `get-metadata`, so that I know about any publications linked to the studies and samples. This would significantly improve traceability. i.e., that citation information is also fetched and preserved alongside other (meta)data.

I would like to grab any Pubmed ID(s) linked to the BioProject ID. If possible, this could be linked additionally to a DOI (as a separate metadata column).

I imagine that we could either (a) embed the citation directly in provenance or (b) just retrieve the pubmed ID/doi and place it in the metadata file for easy parsing later.

PubMed ID appears to be one of the optional metadata categories, and even [searching BioProjects by PubMed ID is possible in SRA](https://academic.oup.com/nar/article/40/D1/D57/2903284).

This could also be part of a separate action if PubMed ID needs to be fetched via a separate query.

**Comment by misialq** [comment]
This issue describes a slightly different scenario than the one addressed in #113. Here we would need to fetch DOIs/Pubmed IDs given an existing list of BioProject IDs - without the step of going through a Zotero library (not all the IDs necessarily need to originate from publications). However, based on my brief investigation, unfortunately, I don't think it is possible to actually do it (see comment above) so I am indeed closing this issue.
