### ISSUE TITLE
SRA Toolkit still not properly configured after installation

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-fondue#130]
It turns out that when installing fondue (+SRA Toolkit) by following the installation instructions , the SRA Toolkit appears not to be properly configured if it had never been installed on the system before.

**Steps to reproduce:**
1. To mimic a clean OS, start up a virtual machine using e.g. [Vagrant](https://learn.hashicorp.com/collections/vagrant/getting-started).
2. Follow the installation instructions from the README.
3. After activating the `fondue` environment, try to run any of the SRA Toolkit's executables. For example, run `prefetch`.

**Expected behaviour:**
Prefetch's help is displayed.

**Actual behaviour:**
An error message is displayed:
```
This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
```

**Notes:**
This can be solved by running `vdb-config -i`, even without changing any of the settings. My suggestion would be to just leave those configuration steps up to the user after all - we can just add a line to the README saying what they need to run. This would also become an issue when installing through conda, so it would be easier if the users can just run it themselves. Also, having thought about it, maybe we should leave it up to them to decide where the cache location is rather then put it in the home directory by default (as it is now).

**Comment by adamovanja** [comment]
Thanks for documenting this. 
If we include `vdb-config -i` in the ReadMe, I suggest we include our recommendation of settings with it. 

Could we not just include `vdb-config -i` without any setting changes within and a save exit (`x`) in the `install-sra-tools.sh` script? Then we could always mention in the ReadMe that the (very set-up affine) user can further motify this by running `vdb-config -i`.

**Comment by misialq** [comment]
Yes, that would be my preferred option too, I think (I mean, just run it and exit).

**Comment by misialq** [comment]
Oh wait, sorry, no. That would be possible if you run the script yourself but if you install from conda then its more complicated. That's why the best would be to let the user just run it themselves (they could still do it without altering any settings). And maybe it's not so bad to make them aware there actually are some things to be set for the SRA Toolkit (just by stating those in the readme) - that could potentially save us some issues in the future...

**Comment by adamovanja** [comment]
agreed 👍🏼 I would also add [this link](https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration) as a resource for interested users.
