### ISSUE TITLE
Error when downloading data from NCBI

### ISSUE THREAD

**Issue by vgenisel** [bokulich-lab/q2-fondue#157]
Hello,
I tried to run the q2-fondue tutorial a few times but without success. 
The function qiime fondue get all is reporting an error:
"Neither single- nor paired-end sequences could be downloaded. Please check your accession IDs".
Did someone have the same issue or know how to solve it?

I also get the same error when trying to download different data.

![image](https://github.com/bokulich-lab/q2-fondue/assets/109127063/9e3e62c4-05c2-4dbf-8d80-ef71796f3875)

**Comment by adamovanja** [comment]
Hi @vgenisel, 
I was not able to reproduce your error with the same accession IDs. So it seems like you haven't set up q2-fondue fully. Did you follow all the steps from [mandatory configuration instructions](https://github.com/bokulich-lab/q2-fondue/blob/1ed64bfd3953cfa74a9dd6aace43062d1b074549/README.md?plain=1#L44-L62) (especially `vdb-config -i`)? 
Let me know if the issue persists after running these steps.

**Comment by vgenisel** [comment]
Hi @adamovanja ,
I'm happy to say that after re-installing qiime2, mamba, and q-fondue, the plugin is working now. I have followed all the steps from the installation tutorial, but probably some files got corrupted in the process. Deleting everything and starting from scratch fixed it!
Many thanks for your help :D

**Comment by adamovanja** [comment]
Hi @vgenisel, I am glad to hear it is all working now. Happy coding!
