### ISSUE TITLE
Update diagram on fetching metadata

### ISSUE THREAD

**Issue by adamovanja** [bokulich-lab/q2-fondue#31]
As a plugin user, 
I want to have an overview diagram showing me what is happening under the hood of the get-metadata action.

Note: initial draft for this diagram is in #26

**Comment by adamovanja** [comment]
I think this has already been adressed with figure 3 in our preprint. Or do you see anything else that needs to be done here @misialq?

**Comment by misialq** [comment]
I think we meant here more of a flow diagram and what we have in the preprint only partly addresses that... At the same time, I'm anticipating some more changes coming in the future in terms of parallelization so I think yes, we can close it for now and just revive, if necessary, when the time comes. Thanks!
